### ISSUE TITLE
error when running Gesture_Controller.py

### ISSUE THREAD

**Issue by yizhz** [xenon-19/Gesture-Controlled-Virtual-Mouse#17]
I encounter the following error when running Gesture_Controller.py: 

  File "C:\Users\yiyun.zy\anaconda3\envs\py385\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\yiyun.zy\Desktop\xuelangyun\gesture_control\venv\lib\site-packages\cv2\gapi\__init__.py", line 290, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

How can I solve it? Thank you so much

**Comment by ankit-4129** [comment]
Please provide more information,

1. Python version
2. Complete error log

**Comment by ankit-4129** [comment]
try this
```
pip install "opencv-python-headless<4.3"
```
reference: https://stackoverflow.com/questions/72545779/cv2-not-work-after-install-mediapipe-library/72625417

**Comment by yizhz** [comment]
> try this
> 
> ```
> pip install "opencv-python-headless<4.3"
> ```
> 
> reference: https://stackoverflow.com/questions/72545779/cv2-not-work-after-install-mediapipe-library/72625417

I then get "ImportError: DLL load failed while importing win32api: No module named win32api"

I tried uninstall and install, tried pip install pywin32==227, tried python pywin32_postinstall.py -install. But none works

**Comment by padminipriya69** [comment]
> I encounter the following error when running Gesture_Controller.py:
> 
> File "C:\Users\yiyun.zy\anaconda3\envs\py385\lib\importlib__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "C:\Users\yiyun.zy\Desktop\xuelangyun\gesture_control\venv\lib\site-packages\cv2\gapi__init__.py", line 290, in cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
> 
> How can I solve it? Thank you so much



I am facing the exact same issue, can you please help me out

**Comment by ansariyusra** [comment]
hey ! facing the same issue here , did you get any resolution to it??

**Comment by padminipriya69** [comment]
No, not yet, I am currently working on that project, maybe if I get any
solution, I will let you know.
If you find any solution, please let me know

**Comment by tommeuh** [comment]
Hello, same problem with the same configuration then tutorial installation : 
python Gesture_Controller.py
#Traceback (most recent call last):
  File "Gesture_Controller.py", line 3, in <module>
    import cv2
  File "C:\Users\tomle\anaconda3\envs\gest\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\tomle\anaconda3\envs\gest\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\tomle\anaconda3\envs\gest\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\tomle\anaconda3\envs\gest\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\tomle\anaconda3\envs\gest\lib\site-packages\cv2\gapi\__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

**Comment by padminipriya69** [comment]
I got the same error as you, I followed these steps and now I can run the project.

1. For this error
`AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)`
I did this
```
pip uninstall opencv-python
pip uninstall opencv-contrib-python
pip uninstall opencv-contrib-python-headless
and then
pip3 install opencv-contrib-python==4.5.5.62
```
reference: [https://stackoverflow.com/questions/72706073/attributeerror-partially-initialized-module-cv2-has-no-attribute-gapi-wip-gs](url)

2. When I executed after making the above changes, I got the following error.

![image](https://user-images.githubusercontent.com/78025329/211141990-358a6403-106f-466d-bbe7-2e264228fe02.png)
that is solved by
`pip install protobuf==3.20.*`
reference: [https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly](url)

Finally when I run this, I got the correct output
`python Gesture_Controller.py`

I hope it Helps.

**Comment by musavveer** [comment]
> > try this
> > ```
> > pip install "opencv-python-headless<4.3"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > reference: https://stackoverflow.com/questions/72545779/cv2-not-work-after-install-mediapipe-library/72625417
> 
> I then get "ImportError: DLL load failed while importing win32api: No module named win32api"
> 
> I tried uninstall and install, tried pip install pywin32==227, tried python pywin32_postinstall.py -install. But none works

Did you fix this issue? 
I guess you are working on mac os

**Comment by musavveer** [comment]
@xenon-19 @Viral-Doshi @ankit-4129 @parth-12 
I am getting this error:
`Traceback (most recent call last):
  File "/Users/musavveer/spam/02_Grp_GestureAndVoiceControlledVirtualMouse/code/src/Gesture_Controller.py", line 3, in <module>
    import cv2
  File "/Users/musavveer/opt/anaconda3/envs/gest/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/musavveer/opt/anaconda3/envs/gest/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/Users/musavveer/opt/anaconda3/envs/gest/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/Users/musavveer/opt/anaconda3/envs/gest/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/musavveer/opt/anaconda3/envs/gest/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)`

**Comment by musavveer** [comment]
> I got the same error as you, I followed these steps and now I can run the project.
> 
> 1. For this error
>    `AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)`
>    I did this
> 
> ```
> pip uninstall opencv-python
> pip uninstall opencv-contrib-python
> pip uninstall opencv-contrib-python-headless
> and then
> pip3 install opencv-contrib-python==4.5.5.62
> ```
> 
> reference: [https://stackoverflow.com/questions/72706073/attributeerror-partially-initialized-module-cv2-has-no-attribute-gapi-wip-gs](url)
> 
> 2. When I executed after making the above changes, I got the following error.
> 
> ![image](https://user-images.githubusercontent.com/78025329/211141990-358a6403-106f-466d-bbe7-2e264228fe02.png) that is solved by `pip install protobuf==3.20.*` reference: [https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly](url)
> 
> Finally when I run this, I got the correct output `python Gesture_Controller.py`
> 
> I hope it Helps.

HI can you help me fixing the issue

**Comment by prashant963951** [comment]
> I got the same error as you, I followed these steps and now I can run the project.
> 
> 1. For this error
>    `AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)`
>    I did this
> 
> ```
> pip uninstall opencv-python
> pip uninstall opencv-contrib-python
> pip uninstall opencv-contrib-python-headless
> and then
> pip3 install opencv-contrib-python==4.5.5.62
> ```
> 
> reference: [https://stackoverflow.com/questions/72706073/attributeerror-partially-initialized-module-cv2-has-no-attribute-gapi-wip-gs](url)
> 
> 2. When I executed after making the above changes, I got the following error.
> 
> ![image](https://user-images.githubusercontent.com/78025329/211141990-358a6403-106f-466d-bbe7-2e264228fe02.png) that is solved by `pip install protobuf==3.20.*` reference: [https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly](url)
> 
> Finally when I run this, I got the correct output `python Gesture_Controller.py`
> 
> I hope it Helps.

error is resolve but the not get the output

**Comment by joshuacodes07** [comment]
Hello,
I exactly did what u said uninstalled pip and also installed protobuf==3.20.* pip but,
the code is not showing output and it also not showing any errors.
what should i do now.
even commented and uncommented the last two lines.
Can you help me with this as soon as possible.
![Screenshot (26)](https://user-images.githubusercontent.com/130309410/231603685-e034ef48-0dbd-4b45-83ee-0eef25debc90.png)

**Comment by Rashid941** [comment]
(gest) C:\Users\Admin\OneDrive\Desktop\Gesture-COntrolled-Virtual-Mouse\src>python Gesture_Controller.py

(gest) C:\Users\Admin\OneDrive\Desktop\Gesture-COntrolled-Virtual-Mouse\src>

**Comment by asdf500** [comment]
> (gest) C:\Users\Admin\OneDrive\Desktop\Gesture-COntrolled-Virtual-Mouse\src>python Gesture_Controller.py
> 
> (gest) C:\Users\Admin\OneDrive\Desktop\Gesture-COntrolled-Virtual-Mouse\src>

for me also same thing is happening did u solve it..

**Comment by prashant963951** [comment]
Yes
