### ISSUE TITLE
OPENCV error, what is correct version of opencv we need to use?

### ISSUE THREAD

**Issue by mannuramesh** [xenon-19/Gesture-Controlled-Virtual-Mouse#38]
python Proton.py
Traceback (most recent call last):
  File "Proton.py", line 8, in <module>
    import pyautogui
  File "C:\Users\Manoj\.conda\envs\gest\lib\site-packages\pyautogui\__init__.py", line 183, in <module>
    import pyscreeze
  File "C:\Users\Manoj\.conda\envs\gest\lib\site-packages\pyscreeze\__init__.py", line 27, in <module>
    import cv2
  File "C:\Users\Manoj\.conda\envs\gest\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\Manoj\.conda\envs\gest\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\Manoj\.conda\envs\gest\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\Manoj\.conda\envs\gest\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Manoj\.conda\envs\gest\lib\site-packages\cv2\gapi\__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

**Comment by mannuramesh** [comment]
please release the solution by anyone watching
